/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databasecoffeshop;

import javax.swing.JOptionPane;

/**
 *
 * @author Iqbal
 */
public class CoffeshopMenu extends javax.swing.JFrame {

    /**
     * Creates new form CoffeshopMenu
     */
    public CoffeshopMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RadMineral = new javax.swing.JRadioButton();
        RadAmericano = new javax.swing.JRadioButton();
        RadCapuccino = new javax.swing.JRadioButton();
        RadVanilla = new javax.swing.JRadioButton();
        CheckCoffe = new javax.swing.JCheckBox();
        CheckFrench = new javax.swing.JCheckBox();
        CheckBurger = new javax.swing.JCheckBox();
        CheckSpaghetti = new javax.swing.JCheckBox();
        BtnEnter = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        TxtTot = new javax.swing.JTextField();
        BtnBayar = new javax.swing.JButton();
        TxtTax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtPesanan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnKembali.setText("Kembali");
        BtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembaliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("COFFE SHOP MENU");

        RadMineral.setText("Mineral Water (10000)");
        RadMineral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadMineralActionPerformed(evt);
            }
        });

        RadAmericano.setText("Americano (20000)");
        RadAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadAmericanoActionPerformed(evt);
            }
        });

        RadCapuccino.setText("Cappucino (25000)");
        RadCapuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadCapuccinoActionPerformed(evt);
            }
        });

        RadVanilla.setText("Vanilla Latte (28000)");
        RadVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadVanillaActionPerformed(evt);
            }
        });

        CheckCoffe.setText("Coffe Bun (15000)");
        CheckCoffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckCoffeActionPerformed(evt);
            }
        });

        CheckFrench.setText("French Fries (18000)");
        CheckFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckFrenchActionPerformed(evt);
            }
        });

        CheckBurger.setText("Burger (25000)");
        CheckBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBurgerActionPerformed(evt);
            }
        });

        CheckSpaghetti.setText("Spaghetti (20000)");
        CheckSpaghetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSpaghettiActionPerformed(evt);
            }
        });

        BtnEnter.setText("Enter");
        BtnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnterActionPerformed(evt);
            }
        });

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        jLabel2.setText("Subtotal");

        jLabel3.setText("Taxfee");

        jLabel4.setText("Total");

        BtnBayar.setText("Bayar");
        BtnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBayarActionPerformed(evt);
            }
        });

        jLabel5.setText("No Pesanan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnEnter)
                            .addComponent(BtnDelete)
                            .addComponent(BtnKembali)
                            .addComponent(BtnBayar))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(TxtPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadMineral)
                            .addComponent(RadAmericano)
                            .addComponent(RadCapuccino)
                            .addComponent(RadVanilla))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckFrench)
                            .addComponent(CheckCoffe)
                            .addComponent(CheckBurger)
                            .addComponent(CheckSpaghetti))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadMineral)
                    .addComponent(CheckCoffe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadAmericano)
                    .addComponent(CheckFrench))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadCapuccino)
                    .addComponent(CheckBurger))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadVanilla)
                    .addComponent(CheckSpaghetti))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEnter)
                    .addComponent(jLabel2)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDelete)
                    .addComponent(jLabel3)
                    .addComponent(TxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(BtnBayar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnKembali)
                    .addComponent(jLabel5)
                    .addComponent(TxtPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembaliActionPerformed
        // TODO add your handling code here:
        CoffeshopOpsi opsi = new CoffeshopOpsi();
        opsi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnKembaliActionPerformed

    private void RadMineralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadMineralActionPerformed
        // TODO add your handling code here:
        if (RadMineral.isSelected())
            RadAmericano.setSelected(false);
            RadCapuccino.setSelected(false);
            RadVanilla.setSelected(false);
    }//GEN-LAST:event_RadMineralActionPerformed

    private void RadAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadAmericanoActionPerformed
        // TODO add your handling code here:
        if (RadAmericano.isSelected())
            RadMineral.setSelected(false);
            RadCapuccino.setSelected(false);
            RadVanilla.setSelected(false);
    }//GEN-LAST:event_RadAmericanoActionPerformed

    private void RadCapuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadCapuccinoActionPerformed
        // TODO add your handling code here:
        if (RadCapuccino.isSelected())
            RadMineral.setSelected(false);
            RadAmericano.setSelected(false);
            RadVanilla.setSelected(false);
    }//GEN-LAST:event_RadCapuccinoActionPerformed

    private void RadVanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadVanillaActionPerformed
        // TODO add your handling code here:
        if (RadVanilla.isSelected())
            RadMineral.setSelected(false);
            RadAmericano.setSelected(false);
            RadCapuccino.setSelected(false);
    }//GEN-LAST:event_RadVanillaActionPerformed

    private void CheckCoffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckCoffeActionPerformed
        // TODO add your handling code here:
        if (CheckCoffe.isSelected())
            CheckBurger.setSelected(false);
            CheckFrench.setSelected(false);
            CheckSpaghetti.setSelected(false);
    }//GEN-LAST:event_CheckCoffeActionPerformed

    private void CheckFrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckFrenchActionPerformed
        // TODO add your handling code here:
        if (CheckFrench.isSelected())
            CheckBurger.setSelected(false);
            CheckCoffe.setSelected(false);
            CheckSpaghetti.setSelected(false);
    }//GEN-LAST:event_CheckFrenchActionPerformed

    private void CheckBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBurgerActionPerformed
        // TODO add your handling code here:
        if (CheckBurger.isSelected())
            CheckCoffe.setSelected(false);
            CheckFrench.setSelected(false);
            CheckSpaghetti.setSelected(false);
    }//GEN-LAST:event_CheckBurgerActionPerformed

    private void CheckSpaghettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSpaghettiActionPerformed
        // TODO add your handling code here:
        if (CheckSpaghetti.isSelected())
            CheckBurger.setSelected(false);
            CheckFrench.setSelected(false);
            CheckCoffe.setSelected(false);
    }//GEN-LAST:event_CheckSpaghettiActionPerformed

    private void BtnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnterActionPerformed
        // TODO add your handling code here:
        double total;
        double subtotal = 0;
        final double taxrate= 2000;
        double tax;
        
        if (RadMineral.isSelected()) {
            subtotal = subtotal+10000;
        }else if (RadAmericano.isSelected()){
            subtotal = subtotal+20000;
        }else if (RadVanilla.isSelected()){
            subtotal = subtotal+28000;
        }else if (RadCapuccino.isSelected()){
            subtotal = subtotal+25000;
        }
        
        if (CheckCoffe.isSelected()){
            subtotal = subtotal+15000;
        }else if (CheckFrench.isSelected()){
            subtotal= subtotal+18000;
        }else if (CheckBurger.isSelected()){
            subtotal = subtotal+25000;
        }else if (CheckSpaghetti.isSelected()){
            subtotal = subtotal+20000;
        }
        
        
        txtSubtotal.setText(Double.toString(subtotal));
        
        subtotal = Double.parseDouble(txtSubtotal.getText());
        tax = taxrate;
        total = tax+subtotal;
        
        TxtTax.setText(Double.toString(tax));
        TxtTot.setText(Double.toString(total));
        
        JOptionPane.showMessageDialog(null, "Please Click Bayar Button!");
    }//GEN-LAST:event_BtnEnterActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        RadMineral.setSelected(false);
        RadAmericano.setSelected(false);
        RadVanilla.setSelected(false);
        RadCapuccino.setSelected(false);
        CheckSpaghetti.setSelected(false);
        CheckFrench.setSelected(false);
        CheckCoffe.setSelected(false);
        CheckBurger.setSelected(false);
        TxtTax.setText("");
        txtSubtotal.setText("");
        TxtTot.setText("");
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBayarActionPerformed
        // TODO add your handling code here:
        CoffeshopPay pay = new CoffeshopPay();
        pay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeshopMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeshopMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeshopMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeshopMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeshopMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBayar;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnEnter;
    private javax.swing.JButton BtnKembali;
    private javax.swing.JCheckBox CheckBurger;
    private javax.swing.JCheckBox CheckCoffe;
    private javax.swing.JCheckBox CheckFrench;
    private javax.swing.JCheckBox CheckSpaghetti;
    private javax.swing.JRadioButton RadAmericano;
    private javax.swing.JRadioButton RadCapuccino;
    private javax.swing.JRadioButton RadMineral;
    private javax.swing.JRadioButton RadVanilla;
    private javax.swing.JTextField TxtPesanan;
    private javax.swing.JTextField TxtTax;
    private javax.swing.JTextField TxtTot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtSubtotal;
    // End of variables declaration//GEN-END:variables
}
